"""Verify independent official XRay and sing-box IPK builds.

Also asserts the packaging contract the maintainer review called out: the
control metadata is generated by ares-package and each package registers its
own Luna service while retaining the pinned ARM payload.
"""

import gzip
import hashlib
import io
import json
import os
import struct
import subprocess
import sys
import tarfile
import tempfile


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILDER = os.path.join(ROOT, "build_ipk.py")
VERSION = "4.0.4"


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def read_ar(path):
    with open(path, "rb") as handle:
        payload = handle.read()
    assert payload.startswith(b"!<arch>\n"), "invalid ar magic"
    members = {}
    offset = 8
    while offset < len(payload):
        header = payload[offset : offset + 60]
        assert len(header) == 60 and header[58:60] == b"`\n", "invalid ar header"
        name = header[:16].decode("ascii").strip().rstrip("/")
        size = int(header[48:58].decode("ascii").strip())
        offset += 60
        members[name] = payload[offset : offset + size]
        offset += size + (size % 2)
    return payload, members


def read_tar_members(compressed):
    raw = gzip.decompress(compressed)
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:") as archive:
        result = {}
        modes = {}
        for member in archive.getmembers():
            if member.isfile():
                result[member.name] = archive.extractfile(member).read()
                modes[member.name] = member.mode
        return result, modes


def build(output_dir, edition):
    command = [sys.executable, BUILDER, "--edition", edition, "--output-dir", output_dir]
    subprocess.run(command, cwd=ROOT, check=True)


def elf_machine(data):
    if len(data) < 20 or data[:4] != b"ELF":
        return None
    little = data[5] == 1
    return struct.unpack("<H" if little else ">H", data[18:20])[0]


def verify(path, expected):
    payload, ar_members = read_ar(path)
    assert set(ar_members) == {"debian-binary", "control.tar.gz", "data.tar.gz"}
    assert ar_members["debian-binary"] == b"2.0\n"
    control, control_modes = read_tar_members(ar_members["control.tar.gz"])
    data, data_modes = read_tar_members(ar_members["data.tar.gz"])

    # webOS does not run Debian maintainer scripts; shipping them would imply
    # initialization that never happens.
    for hook in ("preinst", "postinst", "prerm", "postrm"):
        assert hook not in control, "control.tar.gz must not contain " + hook
    assert set(control) == {"control"}, "control archive must hold only 'control'"

    control_text = control["control"].decode("utf-8")
    assert "Package: %s\n" % expected["app_id"] in control_text
    assert "Version: %s\n" % VERSION in control_text
    # ares-package creates this file itself; its write mode follows the host
    # umask (commonly 0644 or 0664), so verify safe readability rather than
    # imposing a mode the official tool does not promise.
    assert control_modes["control"] & 0o444 == 0o444
    assert control_modes["control"] & 0o111 == 0
    assert "Installed-Size: " in control_text
    assert "webOS-Package-Format-Version: 2\n" in control_text
    assert "webOS-Packager-Version: " in control_text
    # ares-package classifies HTML-entry-point applications as web packages;
    # the ARM nature of every bundled helper is verified independently below.
    assert "Architecture: all\n" in control_text

    prefix = "usr/palm/applications/" + expected["app_id"] + "/"
    service_prefix = "usr/palm/services/" + expected["service_id"] + "/"

    appinfo = json.loads(data[prefix + "appinfo.json"].decode("utf-8"))
    assert appinfo["id"] == expected["app_id"]
    assert appinfo["version"] == VERSION
    assert appinfo["title"] == expected["title"]

    packageinfo_path = "usr/palm/packages/" + expected["app_id"] + "/packageinfo.json"
    packageinfo = json.loads(data[packageinfo_path].decode("utf-8"))
    assert packageinfo["app"] == expected["app_id"]
    assert packageinfo["services"] == [expected["service_id"]], packageinfo
    assert data_modes[packageinfo_path] & 0o444 == 0o444
    assert data_modes[packageinfo_path] & 0o111 == 0

    # The Luna service must be present and correctly identified.
    assert service_prefix + "service.js" in data, "service entry point missing"
    service_pkg = json.loads(data[service_prefix + "package.json"].decode("utf-8"))
    assert service_pkg["name"] == expected["service_id"]
    assert service_pkg["main"] == "service.js"
    services_json = json.loads(data[service_prefix + "services.json"].decode("utf-8"))
    assert services_json["id"] == expected["service_id"]
    assert services_json["services"][0]["name"] == expected["service_id"]
    assert services_json["services"][0]["commands"], "service must declare its commands"

    roles_json = json.loads(data[service_prefix + "roles.json"].decode("utf-8"))
    assert roles_json["allowedNames"] == [expected["service_id"]]
    assert roles_json["permissions"][0]["inbound"] == [expected["app_id"]]
    assert "*" not in roles_json["permissions"][0]["inbound"]
    assert service_prefix + "role.json" in data
    ca_path = service_prefix + "certs/cacert.pem"
    assert ca_path in data, "current TLS trust bundle missing"
    if os.name != "nt":
        assert sha256(data[ca_path]) == "3ff344e30b9b1ed2971044eabb438a08f2e2245ddb5f8ab1a3ad8b63ab4eaf91"
    assert data[ca_path].count(b"-----BEGIN CERTIFICATE-----") == 119

    # Luna forbids '-' in service names, and the id must extend the app id.
    assert "-" not in expected["service_id"]
    assert expected["service_id"].startswith(expected["app_id"] + ".")

    edition_json = json.loads(data[service_prefix + "edition.json"].decode("utf-8"))
    assert edition_json["dataDir"] == expected["data_dir"]
    assert edition_json["serviceId"] == expected["service_id"]

    edition_js = data[prefix + "edition.js"].decode("utf-8")
    assert expected["core"] in edition_js
    assert expected["service_id"] in edition_js

    # Both interfaces ship the exact same effective country mapping. The TV
    # loads it before app.js; the service uses its byte-identical copy when
    # rendering Unicode emoji flags for the web importer.
    app_countries = data[prefix + "countries.js"]
    service_countries = data[service_prefix + "countries.js"]
    assert app_countries == service_countries
    index_html = data[prefix + "index.html"].decode("utf-8")
    assert index_html.index('src="countries.js"') < index_html.index('src="app.js"')

    # The retired shell control script and web monolith must be gone.
    assert not any("alcyonectl" in name for name in data), "shell control script must not ship"
    assert not any("alcyone-web" in name for name in data), "web monolith must not ship"

    if expected["core"] == "xray":
        assert prefix + "bin/xray" in data
        assert prefix + "bin/tun2socks" in data
        assert prefix + "bin/sing-box" not in data
        assert sha256(data[prefix + "bin/xray"]) == "451bfccf7c86f08860296903479d8b92edccc507312b3eb338de33a7cb3dabfb"
        assert sha256(data[prefix + "bin/tun2socks"]) == "b2bbe63f8144ce67a9f8839541428999302b68cd54fbf14f403c73be75cd719a"
        if os.name != "nt":
            assert data_modes[prefix + "bin/xray"] == 0o755
        assert sha256(data[prefix + "bin/geosite.dat"]) == "adf92de0cfc70e458b399f04c5f912bf42d115ed7e37281b30e2f1c68605e4e9"
        assert sha256(data[prefix + "bin/geoip.dat"]) == "744c97b74c52bae2ac8664fef6ac481d7765cb8432a0df54f0368a88b9b4a354"
        if os.name != "nt":
            assert data_modes[prefix + "bin/geosite.dat"] == 0o644
            assert data_modes[prefix + "bin/geoip.dat"] == 0o644
        natives = ["bin/xray", "bin/tun2socks"]
    else:
        assert prefix + "bin/sing-box" in data
        assert prefix + "bin/xray" not in data
        assert prefix + "bin/tun2socks" not in data
        assert sha256(data[prefix + "bin/sing-box"]) == "e1db083cfc4fd9c6c93ce75eaeab9f6b59b490fe8258cd28e970ede28412f8e6"
        if os.name != "nt":
            assert data_modes[prefix + "bin/sing-box"] == 0o755
        natives = ["bin/sing-box"]

    # Every bundled native binary must really be 32-bit ARM.
    for relative in natives:
        machine = elf_machine(data[prefix + relative])
        assert machine == 40, "%s is not ARM (e_machine=%s)" % (relative, machine)

    return sha256(payload)


def main():
    expected = {
        "xray": {
            "app_id": "com.alcyone.vpn",
            "service_id": "com.alcyone.vpn.service",
            "title": "Alcyone XRay",
            "core": "xray",
            "data_dir": "/var/lib/alcyone",
            "artifact": "Alcyone-XRay_%s.ipk" % VERSION,
        },
        "sing-box": {
            "app_id": "com.alcyone.vpn.singbox",
            "service_id": "com.alcyone.vpn.singbox.service",
            "title": "Alcyone sing-box",
            "core": "sing-box",
            "data_dir": "/var/lib/alcyone-singbox",
            "artifact": "Alcyone-sing-box_%s.ipk" % VERSION,
        },
    }
    with tempfile.TemporaryDirectory(prefix="alcyone-build-test-") as output_dir:
        build(output_dir, "xray")
        assert os.listdir(output_dir) == [expected["xray"]["artifact"]]
        xray_path = os.path.join(output_dir, expected["xray"]["artifact"])
        verify(xray_path, expected["xray"])

        build(output_dir, "sing-box")
        singbox_path = os.path.join(output_dir, expected["sing-box"]["artifact"])
        verify(singbox_path, expected["sing-box"])

    print("independent edition build tests passed")


if __name__ == "__main__":
    main()
