ALCYONE_APP_ID='com.alcyone.vpn'
ALCYONE_AUTOSTART='alcyone-vpn'
ALCYONE_CORE='xray'
ALCYONE_CORE_LABEL='XRay'
ALCYONE_CORE_VERSION='26.3.27'
ALCYONE_DATA_DIR='/var/lib/alcyone'
ALCYONE_EDITION_NAME='XRay Edition'
ALCYONE_TITLE='Alcyone XRay'
ALCYONE_VERSION='3.2.0'
ALCYONE_WEB_PORT='8080'
