"use strict";
var fs = require("fs"),
  path = require("path"),
  atomic = require("./atomic"),
  INIT_DIR = "/var/lib/webosbrew/init.d";
function Autostart(t) {
  ((t = t || {}),
    (this.edition = t.edition),
    (this.logger = t.logger),
    (this.initDir = t.initDir || INIT_DIR),
    (this.hookFile = path.join(this.initDir, this.edition.autostartName)));
}
((Autostart.prototype.script = function () {
  var t = String((this.edition && this.edition.appId) || ""),
    e = String((this.edition && this.edition.serviceId) || "");
  return /^[A-Za-z0-9_.-]+$/.test(t) && /^[A-Za-z0-9_.-]+$/.test(e)
    ? [
        "#!/bin/sh",
        "# Generated by Alcyone. Retries this edition's Luna service at boot.",
        "(",
        '  while :; do',
        '    response="$(luna-send -a ' +
          t +
          " -n 1 -f luna://" +
          e +
          '/autostart \'{}\' 2>/dev/null)" || response=""',
        "    compact_response=\"$(printf '%s' \"$response\" | tr -d '[:space:]')\"",
        '    case "$compact_response" in',
        "      *'\"accepted\":true'*) exit 0 ;;",
        "    esac",
        "    sleep 10",
        "  done",
        ") >/dev/null 2>&1 &",
        "exit 0",
        "",
      ].join("\n")
    : "";
}),
  (Autostart.prototype.isEnabled = function () {
    try {
      return (
        fs.statSync(this.hookFile).isFile() &&
        fs.readFileSync(this.hookFile, "utf8") === this.script()
      );
    } catch (t) {
      return !1;
    }
  }),
  (Autostart.prototype.enable = function () {
    var t = this.script();
    if (!t) throw new Error("autostart identity invalid");
    return (
      atomic.ensureSharedDir(this.initDir, atomic.SHARED_DIR_MODE),
      atomic.writeSharedFileAtomic(this.hookFile, t, 493),
      this.logger.info("autostart enabled"),
      !0
    );
  }),
  (Autostart.prototype.disable = function () {
    var t = atomic.removeQuiet(this.hookFile);
    return (t && this.logger.info("autostart disabled"), t);
  }),
  (Autostart.prototype.set = function (t) {
    return t ? this.enable() : this.disable();
  }),
  (Autostart.prototype.repairLegacy = function () {
    try {
      if (!fs.statSync(this.hookFile).isFile()) return !1;
    } catch (t) {
      return !1;
    }
    return (
      !this.isEnabled() &&
      (this.enable(), this.logger.info("legacy autostart hook repaired"), !0)
    );
  }),
  (module.exports = { INIT_DIR: INIT_DIR, Autostart: Autostart }));
