'use strict';

/* Autostart integration.

   Homebrew Channel runs executable hooks in /var/lib/webosbrew/init.d at boot.
   The hook we install is a fixed, generated three-line script that only asks
   the Luna bus to start this edition's service: no user data is interpolated
   into it, and it contains no logic of its own.

   Each edition writes its own uniquely named hook, so the two editions never
   overwrite each other's autostart. */

var fs = require('fs');
var path = require('path');
var atomic = require('./atomic');

var INIT_DIR = '/var/lib/webosbrew/init.d';

function Autostart(options) {
  options = options || {};
  this.edition = options.edition;
  this.logger = options.logger;
  this.initDir = options.initDir || INIT_DIR;
  this.hookFile = path.join(this.initDir, this.edition.autostartName);
}

/* The hook only pokes the bus; all real logic lives in the service. */
Autostart.prototype.script = function () {
  return [
    '#!/bin/sh',
    '# Generated by Alcyone. Starts this edition\'s Luna service at boot.',
    'luna-send -a ' + this.edition.appId + ' -n 1 -f luna://' +
      this.edition.serviceId + '/autostart \'{}\' >/dev/null 2>&1 &',
    ''
  ].join('\n');
};

Autostart.prototype.isEnabled = function () {
  try {
    return fs.statSync(this.hookFile).isFile() &&
      fs.readFileSync(this.hookFile, 'utf8') === this.script();
  } catch (e) {
    return false;
  }
};

Autostart.prototype.enable = function () {
  atomic.ensureDir(this.initDir);
  atomic.writeFileAtomic(this.hookFile, this.script(), 493 /* 0755 */);
  try { fs.chmodSync(this.hookFile, 493); } catch (e) {}
  this.logger.info('autostart enabled');
  return true;
};

Autostart.prototype.disable = function () {
  var removed = atomic.removeQuiet(this.hookFile);
  if (removed) this.logger.info('autostart disabled');
  return removed;
};

Autostart.prototype.set = function (enabled) {
  return enabled ? this.enable() : this.disable();
};

/* Preserve the user's old enabled setting while replacing a legacy hook that
   still points at the deleted shell controller. */
Autostart.prototype.repairLegacy = function () {
  try {
    if (!fs.statSync(this.hookFile).isFile()) return false;
  } catch (e) {
    return false;
  }
  if (this.isEnabled()) return false;
  this.enable();
  this.logger.info('legacy autostart hook repaired');
  return true;
};

module.exports = {
  INIT_DIR: INIT_DIR,
  Autostart: Autostart
};
