'use strict';

/* Input validation for Luna methods and the LAN importer.
   Every public entry point validates here before touching state. Unknown
   fields are rejected so a typo or an injected key cannot reach the store. */

var errors = require('./errors');
var err = errors.err;

var MAX_LINK = 16000;
var MAX_URL = 2048;
var MAX_NAME = 80;
var MAX_ID = 64;

function isPlainObject(value) {
  return !!value && typeof value === 'object' && Object.prototype.toString.call(value) !== '[object Array]';
}

/* Luna delivers a payload object; reject anything else outright. */
function requireObject(payload) {
  if (!isPlainObject(payload)) throw err('INVALID_PARAMS', 'payload must be an object');
  return payload;
}

/* Reject fields we do not understand instead of silently ignoring them. */
function rejectUnknown(payload, allowed) {
  var allowedMap = {}, i, key;
  for (i = 0; i < allowed.length; i++) allowedMap[allowed[i]] = true;
  for (key in payload) {
    if (!Object.prototype.hasOwnProperty.call(payload, key)) continue;
    /* Luna injects these transport keys into every request payload. */
    if (key === '$activity' || key === 'subscribe' || key === '$sender') continue;
    if (!allowedMap[key]) throw err('UNKNOWN_FIELD', key);
  }
  return payload;
}

function optionalBoolean(payload, key, fallback) {
  var value = payload[key];
  if (value === undefined || value === null) return !!fallback;
  if (typeof value !== 'boolean') throw err('INVALID_PARAMS', key + ' must be a boolean');
  return value;
}

/* Identifiers are generated by the store, so we can demand a strict shape. */
function profileId(payload, key, required) {
  var value = payload[key];
  if (value === undefined || value === null || value === '') {
    if (required) throw err('MISSING_FIELD', key);
    return '';
  }
  if (typeof value !== 'string') throw err('INVALID_PROFILE_ID', key + ' must be a string');
  if (value.length > MAX_ID || !/^[A-Za-z0-9_-]+$/.test(value)) throw err('INVALID_PROFILE_ID', key);
  return value;
}

/* Display names are free text but must not carry control characters. */
function displayName(payload, key) {
  var value = payload[key];
  if (value === undefined || value === null) return '';
  if (typeof value !== 'string') throw err('INVALID_PARAMS', key + ' must be a string');
  return value.replace(/[\u0000-\u001f\u007f]/g, '').trim().slice(0, MAX_NAME);
}

function proxyLink(payload, key) {
  var value = payload[key];
  if (typeof value !== 'string' || !value) throw err('MISSING_FIELD', key);
  value = value.replace(/[\u0000-\u001f\u007f]/g, '').trim();
  if (value.length > MAX_LINK) throw err('INVALID_LINK', 'link too long');
  if (!/^(vless|hy2|hysteria2|hysteria|trojan|vmess|ss|socks5?):\/\//i.test(value)) {
    throw err('INVALID_LINK', 'unsupported scheme');
  }
  return value;
}

function subscriptionUrl(payload, key) {
  var value = payload[key];
  if (typeof value !== 'string' || !value) throw err('MISSING_FIELD', key);
  value = value.replace(/[\u0000-\u001f\u007f\s]/g, '').trim();
  if (value.length > MAX_URL) throw err('INVALID_URL', 'url too long');
  if (!/^https?:\/\//i.test(value)) throw err('INVALID_URL', 'only http and https are supported');
  /* Reject embedded credentials here as well as in the SSRF policy, so the
     rejection is consistent whether or not a request is ever attempted. */
  if (/^https?:\/\/[^/?#]*@/i.test(value)) throw err('URL_CREDENTIALS_REJECTED', 'credentials in url');
  return value;
}

function language(payload, key) {
  var value = payload[key];
  if (value !== 'ru' && value !== 'en' && value !== 'auto') throw err('INVALID_LANG', key);
  return value;
}

/* Free-form text arriving from the LAN form: either a proxy link or a URL. */
function importValue(payload, key) {
  var value = payload[key];
  if (typeof value !== 'string' || !value) throw err('MISSING_FIELD', key);
  value = value.replace(/[\u0000-\u001f\u007f]/g, '').trim();
  if (!value) throw err('MISSING_FIELD', key);
  if (value.length > MAX_LINK) throw err('INVALID_LINK', 'value too long');
  return value;
}

module.exports = {
  MAX_LINK: MAX_LINK,
  MAX_URL: MAX_URL,
  MAX_NAME: MAX_NAME,
  isPlainObject: isPlainObject,
  requireObject: requireObject,
  rejectUnknown: rejectUnknown,
  optionalBoolean: optionalBoolean,
  profileId: profileId,
  displayName: displayName,
  proxyLink: proxyLink,
  subscriptionUrl: subscriptionUrl,
  language: language,
  importValue: importValue
};
